apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    {{- if .Values.isClusterService }}
    k8s-app: {{ .Release.Name }}
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Backend"
    {{- else }}
    app: {{ .Release.Name }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- if .Values.isClusterService }}
      k8s-app: {{ .Release.Name }}
      {{- else }}
      app: {{ .Release.Name }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- if .Values.isClusterService }}
        k8s-app: {{ .Release.Name }}
        {{- else }}
        app: {{ .Release.Name }}
        {{- end }}
        release: {{ .Chart.Name | quote }}
    spec:
      containers:
      - name: {{ .Release.Name }} 
        env:
        - name: GITLAB_API
          value: {{ .Values.api }}
        - name: GITLAB_TOKEN
          value: {{ .Values.token }}
        - name: GITLAB_CI_YML
          value: {{ .Values.yaml }}
        - name: DB_USERNAME
          value: {{ .Values.db.user }}
        - name: DB_PASSWORD
          value: {{ .Values.db.password }}
        - name: DB_NAME
          value: {{ .Values.db.name }}
        - name: DB_HOST
          value: {{ .Values.db.host }}
        - name: DB_POOL_SIZE
          value: "{{ .Values.db.pool }}"
        - name: JWT_ISSUER
          value: {{ .Values.jwt.issuer }}
        - name: JWT_KEY
          value: {{ .Values.jwt.key }}
        - name: PROJECT_SEGMENT_ENV
          value: {{ .Values.project.segment_env }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
        - containerPort: 4001
          name: {{ .Release.Name }}
        livenessProbe:
          httpGet:
            path: /
            port: 4001
            scheme: HTTP
          initialDelaySeconds: 180
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 10
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
