apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }} 
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    {{- if .Values.isClusterService }}
    k8s-app: {{ .Chart.Name | quote }}
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Backend"
    {{- else }}
    app: {{ .Release.Name }} 
    {{- end }}
spec:
  selector:
  {{- if .Values.isClusterService }}
    k8s-app: {{ .Release.Name }}
  {{- else }}
    app: {{ .Release.Name }}
  {{- end }}
  ports:
  - name: {{ .Release.Name }}
    port: 4001
  type: {{ .Values.serviceType }}
