# Default values for backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

name: backend

image:
  repository: registry.cncf.ci/cncf/cncf_ci_dashboard_backend
  tag: "latest"
  pullPolicy: Always

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

# isClusterService specifies whether chart should be deployed as cluster-service or normal k8s app.
isClusterService: true

# serviceType specifies type of service to be created for this chart.
serviceType: "ClusterIP"

api: SET GITLAB APISERVER
token: SET GITLAB TOKEN
yaml: SET YAML


